output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.bioinformatics_cluster.cluster_endpoint
}

output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.bioinformatics_cluster.cluster_id
}

output "cluster_iam_role_arn" {
  description = "EKS cluster IAM role ARN"
  value       = module.bioinformatics_cluster.cluster_iam_role_arn
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = var.eks_cluster_name
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.bioinformatics_cluster.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.bioinformatics_cluster.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.bioinformatics_cluster.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = data.terraform_remote_state.vpc.outputs.aws_region
}
