apiVersion: batch/v1
kind: Job
metadata:
  generateName: fastqc-
spec:
  ttlSecondsAfterFinished: 600
  activeDeadlineSeconds: 3600
  template:
    spec:
      containers:
      - name: fastqc
        image: ${AWSID}.dkr.ecr.${REGION}.amazonaws.com/fastqc
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "2"
        env:
          - name: FASTQ
            value: "${INPUT_FILEPATH}"
          - name: OUTPUT_S3
            value: "${OUTPUT_FILEPATH}"
        command: ["/bin/bash", "-c"]
        # args: ["mkdir -p /data/tmp/; aws s3 cp $FASTQ /data/tmp/; fastqc /data/tmp/$(basename $FASTQ); rm -f /data/tmp/$(basename $FASTQ); zip -9 /data/$(basename ${FASTQ%.fastq.gz}).zip /data/tmp/$(basename ${FASTQ%.fastq.gz})*; aws s3 cp /data/$(basename ${FASTQ%.fastq.gz}).zip ${OUTPUT_S3%/}/"]
        args: ["mkdir -p /data/tmp/; s5cmd cp \"$FASTQ\" /data/tmp/; fastqc /data/tmp/$(basename $FASTQ); rm -f /data/tmp/$(basename $FASTQ); zip -9 /data/$(basename ${FASTQ%.fastq.gz}).zip /data/tmp/$(basename ${FASTQ%.fastq.gz})*; s5cmd cp \"/data/$(basename ${FASTQ%.fastq.gz}).zip\" ${OUTPUT_S3%/}/"]
      restartPolicy: Never
  backoffLimit: 2